### ISSUE TITLE
Right arm error

### ISSUE THREAD

**Issue by jlunenburg** [tue-robotics/tue_robocup#434]
Seems it's still there, so fixing is probably not enough

**Comment by MaxBaeten** [comment]
I turned around the sensor print, maybe it is more stable here.
Because definitely the magnet is not loose.

Furtheractions:
1) Replace sensor print. @hvrooy will ask Ruud if we have any spares
2) Replace the TUES030 board in the shoulder, the board that reads out the analog value. There might be something wrong with the adc that reads out that sensor. We might also try to put in on a different input channel.

**Comment by MatthijsBurgh** [comment]
Turned into endstop homing, so problem with the absolute sensor anymore.
