### ISSUE TITLE
Find literature on translucent object segmentation

### ISSUE THREAD

**Issue by LoyVanBeek** [tue-robotics/tue_robocup#505]
There was some RoboCup@Home team a couple of years ago that said they could do this. 

Find out how they do it and see if we can use the same.

**Comment by MatthijsBurgh** [comment]
Homer TDP 2015:
Transparent objects (in our case drinking glasses) are detected by making use of one fault of the structured light sensor. The light emitted by the Xtion camera is scattered in transparent objects, providing no valid depth information. We segment areas with no depth data and compare them with drinking glass contour templates. Since the supporting table plane around the transparent objects has valid depth information, a size and location estimation of the transparent objects is obtained and used for grasping.

**Comment by LoyVanBeek** [comment]
Good find! Can we use this approach in some way?

**Comment by MatthijsBurgh** [comment]
No easy implementation in current pipeline possible. Performance of detection of bottles is improved by https://github.com/tue-robotics/ed_sensor_integration/pull/14.
