### ISSUE TITLE
Person_recognition never exits when WAIT_FOR_OPERATOR fails

### ISSUE THREAD

**Issue by LoyVanBeek** [tue-robotics/tue_robocup#56]
Try with rosrun challenge_person_recognition person_recognition.py mockbot

There is an infinite loop

**Comment by LFBFerreira** [comment]
Is there a person in front of the robot... He can't continue the challenge if he indeed can't see anyone to learn a face

**Comment by LoyVanBeek** [comment]
If there is no-one in front  of the robot, it should decide to fail and move on after some time.

**Comment by LFBFerreira** [comment]
Kind of true, then the rest of the challenge is completly random because it needs to recognize someone. At the time i was confident about detecting a person in front of the robot so i didnt build a workaround for it, but i can change it when i give the challenge an update. Some other states might also crash due to recent changes in ED.

The only challenge that i'm making sure its works, for now, is the test

**Comment by Rayman** [comment]
I think that during the challenge, the best action is just to continue waiting. Something else does not make sense.
