### ISSUE TITLE
Challenge person recognition: Did not recognize a thing

### ISSUE THREAD

**Issue by reinzor** [tue-robotics/tue_robocup#63]

**Comment by LoyVanBeek** [comment]
Last saturday, I made a tue-get target for openface and a basic python implementation in ed_perceptions/tools. 
TODO:

- Bridge to C++ of ed_perception's face_recognition framework
- Persist face representations and associated names (could be a csv file)
- Instead of a SVM classifier, we have to do a simpler similarity check because we only know 1 person and the rest are unknown. This is different from classification.

**Comment by reinzor** [comment]
Fixed during reo2016
