### ISSUE TITLE
Call arm that is in use in smach_states

### ISSUE THREAD

**Issue by LarsJanssenTUe** [tue-robotics/tue_robocup#739]
``` 
    def distance_to_poi_area(self, frame_stamped):

        # ToDo: cook up something better: we need the arm that we're currently using but this would require a
        # rather large API break
        base_offset = self.robot.arms.values()[0].base_offset
        radius = math.hypot(base_offset.x(), base_offset.y())

 ```

In the robot_smach_states/util/designators/ed_designators.py

**Comment by alberth** [comment]
This works by accident at best since you get whatever arm was added first to the dictionary (so lucky it's an ordered dictionary!!) rather than what you're using.

In the general sense, I think we need a better vision how to go about from aims and goals at challenge level to positions, orientations, and movements at hardware level. What information and computation steps are done where?
Note that the mess we now have with arms also holds for any other robot part. Different body / spindle construction, different cameras, different wheels, different base, different ranges and speed of arms, different connections between hardware parts, etc etc.
For a true robot-independent challenge the 'what' needs to be very separated from the 'how'.
