### ISSUE TITLE
Force sensor integration for pickup in the take out the garbage

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue_robocup#783]

**Comment by PetervDooren** [comment]
This can be easily implemented on Hero as there is already a wrist wrench topic. However how should this be implemented so that it will also work for Amigo? If we add this to the arm robot part and depend on the functionality in challenges then we will have to make a wrench sensor for Amigo.

I would suggest to add this to the arm part since we are mainly using Hero. Create an issue to create a wrist wrench sensor for amigo and add that to the backlog.
