### ISSUE TITLE
Single-shot openpose

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue_robocup#784]

**Comment by jlunenburg** [comment]
What does this mean?

**Comment by LoyVanBeek** [comment]
Currently, our openpose-node runs continuously, each camera frame is processed. 
Thais takes a lot of power and drains the backpack laptop on HERO. 

Instead, we want to run openpose as a service: give it an image and let it do it's magic only then.

**Comment by LoyVanBeek** [comment]
@Reinzor, in his great wisdom, already implemented both a topic-listening API **and** a `recognize` service. So, just making the node listen to a non-existing topic (like `/ignore/images/topic/because/we/want/only/service/mode`).
That's something we can do in our launch files instead of our `openpose_node` itself.
